parser: '@typescript-eslint/parser'

env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: [
  'htmlacademy/es6',
  'plugin:react/recommended',
  'plugin:@typescript-eslint/recommended'
]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

rules: {
  "react/prop-types": "off"
}